### ISSUE TITLE
Not building

### ISSUE THREAD

**Issue by zakkak** [LegacyHuawei/local_manifests#9]
Hello,

I am trying to build an image for u8800 from source and it fails.
I am using this local_manifests and the `cm-12.1` branch of the CyanogenMod/android repository as the default manifest.

The error I am getting relates to ION.

```
In file included from hardware/qcom/audio-caf/msm7x30/legacy/AudioHardware.cpp:38:0:
hardware/qcom/audio-caf/msm7x30/legacy/AudioHardware.h:544:87: error: 'ion_user_handle_t' has not been declared
             BuffersAllocated(void *buf1, void *buf2, int32_t nSize, int32_t share_fd, ion_user_handle_t handle) :
                                                                                       ^
hardware/qcom/audio-caf/msm7x30/legacy/AudioHardware.h:547:13: error: 'ion_user_handle_t' does not name a type
             ion_user_handle_t ion_handle;
```

Do you have any hints on what I might be doing wrong?

With a short investigation it seems to me that msm7x30/android_kernel_qcom_msm7x30
is more up-to-date than LegacyHuawei/android_kernel_huawei_msm7x30.

Thanks

**Comment by rtammekivi** [comment]
Hey

Apply latest commits here (regarding ION): https://github.com/LegacyXperia/android_kernel_semc_msm7x30/commits/cm-12.1

I will apply them myself too someday.

The qcom_msm7x30 is 3.10 kernel source (unified for SEMC/Huawei msm7x30), it boots and seems to work quite nicely, however there are some unsolved issues which are not letting us to move to 3.10.

Regards
Rudolf

**Comment by zakkak** [comment]
Thanks @Blefish.

I also had to apply the first part of https://github.com/LegacyHuawei/android_device_huawei_msm7x30-common/commit/eec3850f8a1b28eb910123d0e1c4680ef388daa8.

Do you want me to issue pull requests for those, to make the code on github buildable?

Is there a place I can read about the issues that prevent the move to 3.10 and see if I can help in any way?

**Comment by rtammekivi** [comment]
I was in a rush with the latest changes for 3.10 so I just dumped them all up (some were more or less complete though). The thing is we started moving to device tree solution on 3.10. This would allow us to move close to upstream releases sometime, implying we can fix the drivers that are not converted yet.

The code here is without the wip device tree changes: https://github.com/msm7x30/android_kernel_qcom_msm7x30
Plus some patches that have not been accepted here: http://review.msm7x30.org/#/q/status:open+project:msm7x30/android_kernel_qcom_msm7x30+branch:android-3.10
Some are required to fix the build.

And here's my WIP dump with device tree changes (note it builds kernel with zImage-dt and that must be used when making boot image): https://github.com/Blefish/android_kernel_qcom_msm7x30/commits/dt_pm8xxx

As far as I remember, the issues we had:
- Wi-Fi driver did not build, needed multiple updates from prima driver.
- No early suspend, wifi driver depended on it and now disconnected wifi instead of sleeping (fixable from prima driver).
- Mobile data not working
- Random clock bug (might be Android bug). The clock in status bar was not the same as in lockscreen after a day of uptime or similar.
- MMC driver failed to let the system suspend (mmc1_detect). Wi-Fi related again (polling did not work well afaik).

And from the positive sides:
- Unified kernel for SEMC/Huawei
- We have 3.10, why not move even further now (waiting for DT), since all new drivers have moved to it already)
- KSM and CMA coexist wonderfully, no more camera crashes due to KSM.
- Closer to upstream, minimal clutter from CAF and almost no unused drivers.

Btw, if you want to have the source for libra wi-fi driver, send me a PM or email and register at bitbucket. That allows you to make more changes to kernel source and not to worry about the wifi driver :).

There's no need to upload pull requests, I will apply the commits today and try to build for cm-13.0 if I have the time.
